apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nginx/deployment.yaml
  - nginx/service.yaml
  - nginx/configmap.yaml
  - httpd/deployment.yaml
  - httpd/service.yaml
  - httpd/configmap.yaml
